services:
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  cloud-gateway:
    env_file:
      - .env
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    container_name: cloud-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - resource-service
      - song-service
      - storage-service

  prometheus:
    image: prom/prometheus
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - 3000:3000

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/tempo.yml' ]
    volumes:
      - ./docker/grafana/tempo.yml:/etc/tempo.yml:ro
    ports:
      - "3200:3200" # Tempo API, HTTP ingestion
      - "4318:4318" # OTLP HTTP
      - "4317:4317" # OTLP gRPC (OpenTelemetry traces)

  loki:
    image: grafana/loki:latest # https://hub.docker.com/r/grafana/loki/tags and https://github.com/grafana/loki/releases
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    ports:
      - "3100:3100"

  zipkin:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"
    env_file:
      - .env

  resource-db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_RESOURCE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Maps container port 5432 to host port 5432

  song-db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_SONG_DB}
      POSTGRES_USER: ${POSTGRES_USER}  # Default, can be omitted if unchanged
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"  # Maps container port 5432 to host port 5433 (to avoid conflict)

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: gresau/localstack-persist    # Instead of localstack/localstack, to have persisted resources without pro subscription
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack gateway
      - "127.0.0.1:4510-4559:4510-4559" # External services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-2
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./my-localstack-data:/persisted-data"

  api-client:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    env_file:
      - .env
    build:
      context: ./api-client
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - auth-server
      - storage-service

  auth-server:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    env_file:
      - .env
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  storage-service:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    env_file:
      - .env
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8085/actuator/health | grep UP || exit 1"
      interval: 30s
      retries: 3
      start_period: 1m
      timeout: 10s
    depends_on:
      - eureka-service
      - localstack

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  resource-service:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8081/actuator/health | grep UP || exit 1"
      interval: 30s
      retries: 3
      start_period: 1m
      timeout: 10s
    depends_on:
      - eureka-service
      - resource-db
      - localstack
      - rabbitmq
      - zipkin

  resource-processor:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    links:
      - resource-service
    env_file:
      - .env
    build:
      context: ./resource-processor
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8082/actuator/health | grep UP || exit 1"
      interval: 30s
      retries: 3
      start_period: 120s
      timeout: 10s
    depends_on:
      - rabbitmq
      - resource-service
      - song-service

  song-service:
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    deploy:
      replicas: 2
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
    build:
      context: ./song-service
      dockerfile: Dockerfile
    ports:
      - "8083-8084:8083"
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - eureka-service
      - song-db
