{
 "title": "Logs, Traces, Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "API Gateway performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count[1m])) by (routeId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs with trace ID $traceId",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=~\".+\"} |= `$traceId`"
    }
   ]
  },
  {
   "title": "Trace View for trace with id $traceId",
   "type": "traces",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "68163c30775df980f41e399cfc229d08"
    }
   ]
  },
  {
   "title": "latency for All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  }
 ]
}