global:
  scrape_interval: 2s
scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: resource-service
    scrape_interval: 2s
    metrics_path: /actuator/resource-prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: storage-service
    scrape_interval: 2s
    metrics_path: /actuator/storage-prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: resource-processor
    scrape_interval: 2s
    metrics_path: /actuator/resource-processor-prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: song-service
    scrape_interval: 2s
    metrics_path: /actuator/song-prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: eureka-service
    scrape_interval: 2s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8761
  - job_name: cloud-gateway
    scrape_interval: 2s
    metrics_path: /actuator/gateway-prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
