spring:
  application:
    name: song-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: never

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

management:
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    propagation:
      type: b3
    observations:
      http:
        client:
          enabled: true
        server:
          enabled: true
  endpoints:
    web:
      exposure:
        include: "*"